# Generated by Django 2.2.5 on 2020-05-26 15:28

from django.db import migrations, models
import unlimited_char.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnlimitedExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', unlimited_char.fields.CharField(db_index=True, default='', verbose_name='Name')),
                ('code', unlimited_char.fields.CharField(db_index=True, default='', max_length=12, verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Unlimuted Example',
                'verbose_name_plural': 'Unlimited Examples',
            },
        ),
    ]
